version: "3"
services:
  crdw:
    image: cloudreve/cloudreve
    container_name: crdw
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 443:5212
    volumes:
      - ./:./
    privileged: true
    
  ap:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=EternalFutureSecondDownload
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ./downloads:./downloads
    ports:
      - 6800:6800
# If you use host network mode, then no port mapping is required.
# This is the easiest way to use IPv6 networks.
#    network_mode: host
#    network_mode: bridge
#    ports:
#      - 6800:6800
#      - 6888:6888
#      - 6888:6888/udp
    restart: always
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
