version: "3"
services:
  cloudreve:
    image: cloudreve/cloudreve
    container_name: crdw
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 443:5212
    volumes:
      - ./:./
    privileged: true
